/*
 * ibis-core.js
 * ------------------------------------------------------------------
 * The heart of the tool: a pure assembler that turns a NORMALIZED
 * model-data object into a spec-compliant IBIS v3.2 text file.
 *
 * Every input adapter (square-law, rise/fall, pasted data) is
 * responsible for producing this same normalized shape, so the
 * assembler never needs to know where the numbers came from.
 *
 * Normalized model-data shape:
 * {
 *   component:  "MyChip",
 *   manufacturer: "Unknown",
 *   pkg: { r: 0.1, l: 5e-9, c: 0.5e-12 },       // package parasitics (typ)
 *   model: {
 *     name: "buf",
 *     type: "I/O",                              // I/O | Output | Input | 3-state | Open_drain ...
 *     polarity: "Non-Inverting",
 *     enable:   "Active-High",
 *     vinl: 0.8, vinh: 2.0,
 *     vcc: 1.8, vccMin: 1.62, vccMax: 1.98,
 *     tempTyp: 25, tempMin: 0, tempMax: 85,
 *     ccomp: { typ: 2e-12, min: 1.5e-12, max: 2.5e-12 },
 *     rpin: 0.1, lpin: 3e-9, cpin: 0.3e-12,
 *     // I-V tables: array of { v, typ, min, max } (current in Amps)
 *     pulldown: [...], pullup: [...], gndClamp: [...], powerClamp: [...],
 *     // ramp: dv over dt (dv in V, dt in s) for typ/min/max
 *     ramp: { dvr: 0.6*1.8, dtr: {typ:..,min:..,max:..},
 *             dvf: 0.6*1.8, dtf: {typ:..,min:..,max:..} }
 *   },
 *   pins: [ { num:"1", name:"DQ0", model:"buf" }, ... ],
 *   provenance: "Square-law estimate, node=sky130, ..."   // -> [Notes]
 * }
 * ------------------------------------------------------------------
 */
(function () {
  "use strict";

  function eng(x) {
    // Format a number for IBIS: fixed-ish with enough precision.
    if (x === 0) return "0";
    if (!isFinite(x)) return "0";
    const a = Math.abs(x);
    if (a >= 1e6 || a < 1e-4) return x.toExponential(4);
    return x.toPrecision(6).replace(/\.?0+$/, "");
  }

  // Current column: IBIS wants Amps, printed with a unit-suffixed style
  // is optional; plain scientific notation is fully spec-legal.
  function amp(x) {
    if (x === 0) return "0";
    return x.toExponential(4);
  }

  function volt(x) {
    return (x >= 0 ? " " : "") + x.toFixed(4);
  }

  function ohms(x) {
    if (x == null || !isFinite(x)) return "n/a";
    if (x >= 1000) return (x / 1000).toFixed(2) + " kohm";
    return x.toFixed(1) + " ohm";
  }

  function pad(s, n) {
    s = String(s);
    return s.length >= n ? s : s + " ".repeat(n - s.length);
  }

  function ivTable(title, rows) {
    let out = "[" + title + "]\n";
    out += "|" + pad(" Voltage", 14) + pad("I(typ)", 16) + pad("I(min)", 16) + "I(max)\n";
    rows.forEach(function (r) {
      out += pad(volt(r.v), 15) + pad(amp(r.typ), 16) + pad(amp(r.min), 16) + amp(r.max) + "\n";
    });
    out += "|\n";
    return out;
  }

  function typMinMaxLine(label, obj, fmt) {
    fmt = fmt || eng;
    return pad(label, 14) + pad(fmt(obj.typ), 14) + pad(fmt(obj.min), 14) + fmt(obj.max) + "\n";
  }

  window.IBIS = {
    /**
     * Build the full .ibs text from normalized model data.
     * `dateStr` is passed in from the caller (no Date.now in core).
     */
    build: function (d, dateStr, rev) {
      const m = d.model;
      const fileName = (d.component || "model").toLowerCase().replace(/[^a-z0-9_]/g, "_") + ".ibs";
      let s = "";

      s += "[IBIS Ver]       3.2\n";
      s += "[File Name]      " + fileName + "\n";
      s += "[File Rev]       1.0\n";
      if (dateStr) s += "[Date]           " + dateStr + "\n";
      s += "[Source]         Generated by IBIS Model Builder " + (rev || "") + " (github.com/borenw/ibis-model-builder)\n";
      s += "[Notes]          " + (d.provenance || "First-order behavioral estimate.") + "\n";
      s += "[Disclaimer]     THIS MODEL IS A FIRST-ORDER ESTIMATE. It is NOT foundry-\n";
      s += "|                validated silicon data. Do not use for final sign-off\n";
      s += "|                without correlating against measurement or SPICE.\n";
      s += "\n";

      s += "[Component]      " + (d.component || "MyComponent") + "\n";
      s += "[Manufacturer]   " + (d.manufacturer || "Unknown") + "\n";
      s += "[Package]\n";
      s += "|" + pad(" variable", 13) + pad("typ", 14) + pad("min", 14) + "max\n";
      s += pad("R_pkg", 14) + pad(eng(d.pkg.r), 14) + pad(eng(d.pkg.r), 14) + eng(d.pkg.r) + "\n";
      s += pad("L_pkg", 14) + pad(eng(d.pkg.l), 14) + pad(eng(d.pkg.l), 14) + eng(d.pkg.l) + "\n";
      s += pad("C_pkg", 14) + pad(eng(d.pkg.c), 14) + pad(eng(d.pkg.c), 14) + eng(d.pkg.c) + "\n";
      s += "\n";

      s += "[Pin]  signal_name        model_name          R_pin     L_pin     C_pin\n";
      d.pins.forEach(function (p) {
        s += pad(p.num, 7) + pad(p.name, 19) + pad(p.model, 20) +
             pad(eng(m.rpin), 10) + pad(eng(m.lpin), 10) + eng(m.cpin) + "\n";
      });
      s += "\n";

      // ---- Model ----
      s += "[Model]          " + m.name + "\n";
      s += "Model_type       " + m.type + "\n";
      if (m.polarity) s += "Polarity         " + m.polarity + "\n";
      if (m.enable)   s += "Enable           " + m.enable + "\n";
      s += "Vinl = " + m.vinl + "V\n";
      s += "Vinh = " + m.vinh + "V\n";
      s += "|\n";
      s += "|" + pad(" variable", 13) + pad("typ", 14) + pad("min", 14) + "max\n";
      s += typMinMaxLine("C_comp", m.ccomp);
      s += "|\n";
      s += "[Voltage Range]  " + m.vcc + "\t" + m.vccMin + "\t" + m.vccMax + "\n";
      s += "[Temperature Range] " + m.tempTyp + "\t" + m.tempMin + "\t" + m.tempMax + "\n";
      if (isFinite(m.ronPd) || isFinite(m.ronPu)) {
        s += "|\n";
        s += "| Derived driver output impedance (near-rail slope dV/dI of the I-V tables):\n";
        s += "|   Pulldown R_on ~ " + ohms(m.ronPd) + "     Pullup R_on ~ " + ohms(m.ronPu) + "\n";
        s += "| NOTE: informational only -- IBIS carries no driver resistance; the drive\n";
        s += "|       is the [Pulldown]/[Pullup] I-V tables below. R = V/I along the curve.\n";
      }
      s += "\n";

      if (m.pulldown && m.pulldown.length)   s += ivTable("Pulldown", m.pulldown) + "\n";
      if (m.pullup && m.pullup.length)       s += ivTable("Pullup", m.pullup) + "\n";
      if (m.gndClamp && m.gndClamp.length)   s += ivTable("GND Clamp", m.gndClamp) + "\n";
      if (m.powerClamp && m.powerClamp.length) s += ivTable("POWER Clamp", m.powerClamp) + "\n";

      // ---- Ramp ----
      if (m.ramp) {
        s += "[Ramp]\n";
        s += "|" + pad(" variable", 13) + pad("typ", 20) + pad("min", 20) + "max\n";
        s += pad("dV/dt_r", 14) +
             pad(rampCell(m.ramp.dvr, m.ramp.dtr.typ), 20) +
             pad(rampCell(m.ramp.dvr, m.ramp.dtr.min), 20) +
             rampCell(m.ramp.dvr, m.ramp.dtr.max) + "\n";
        s += pad("dV/dt_f", 14) +
             pad(rampCell(m.ramp.dvf, m.ramp.dtf.typ), 20) +
             pad(rampCell(m.ramp.dvf, m.ramp.dtf.min), 20) +
             rampCell(m.ramp.dvf, m.ramp.dtf.max) + "\n";
        s += "R_load = " + (m.ramp.rload || 50) + "\n";
        s += "\n";
      }

      s += "[End]\n";
      return s;
    }
  };

  function rampCell(dv, dt) {
    // IBIS ramp cell is "dV/dt" written literally as "<dv>/<dt>"
    return eng(dv) + "/" + amp(dt).replace("e", "e");
  }
})();
